export const LangData = {
  en: {
    projectName: "Nikki Project Manager",
    firstUseWelcome: "Welcome to Nikki Project Manager",
    firstUseContent: `<strong>Press CTRL+D at any time to display the help page.</strong> <br /> Since this is the first time you're using this application, please setup the next default values to be used by the application. <br/> <br/> All the settings can be
		<strong>modified </strong> at any time.`,
    firstUseSetupFolder: "Setup the default folder to store your projects.",
    firstUseSetupColor: "Setup the default application color",
    aboutContent:
      "Nikki Project Manager is a standalone Kanban board built with Electron and Vue.js. It supports Windows, Linux, and macOS. It is free and open source under the AGPLv3 license.<br /><br /><br /> <strong>Source: </strong> <a href=\"https://github.com/nikkimasani/topsi-project-manager\">https://github.com/nikkimasani/topsi-project-manager</a>",
    searchLabel: "Search by title, tags, project...",
    helperTitle: "Helper/Shortcuts",
    newMilestoneLabel: "Milestone Name",
    category: "Category",
    milestone: "Milestone",
    noTagFound: "No tag found. Tags needs to be created before being used.",
    projectDialogFolderLabel: "Project's save directory",
    newProject: "New project",
    exportProject: "Export Project",
    importProject: "Import Project",
    settings: "Settings",
    layoutAndOptions: "Layout & Options",
    project: "Project",
    title: "Title",
    tags: "Tags",
    backToProjects: "Back to projects",
    searchInNotes: "Search in notes (CTRL + F)",
    addNewNote: "Add a new Note",
    editProject: "Edit Project",
    milestones: "Milestones",
    noTagsCreated: "No tags created yet. ",
    confirmDeleteMessage: "Are you sure you want to delete this project ?",
    export: "Export",
    general: "General",
    about: "About",
    darkMode: "Dark Mode",
    darkenToolbar: "Darken Toolbar",
    language: "Language",
    tasks: "Tasks",
    newTask: "New task",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    browse: "Browse",
    done: "Done",
    close: "Close",
    delete: "Delete",
    add: "Add"
  },
  zh: {
    projectName: "Nikki 项目管理",
    firstUseWelcome: "欢迎使用 Nikki 项目管理",
    firstUseContent: `<strong>任何时候按下 CTRL+D 可以显示帮助页面.</strong> <br /> 由于这是你第一次使用这个应用，请设置应用程序要使用的默认值 <br/> <br/> 所有设置在任何时候都可以<strong>修改 </strong>。`,
    firstUseSetupFolder: "设置默认的文件夹去保存你的项目。",
    firstUseSetupColor: "设置项目默认颜色",
    aboutContent:
      "Nikki 项目管理是一个独立的、基于 Electron 和 Vue.js 的看板软件。它支持 Windows、Linux 和 macOS，并基于 AGPLv3 协议免费开源。<br /><br /><br /> <strong>源码：</strong> <a href=\"https://github.com/nikkimasani/topsi-project-manager\">https://github.com/nikkimasani/topsi-project-manager</a>",
    searchLabel: "搜索标题、标签、项目... ...",
    helperTitle: "帮助/快捷键",
    newMilestoneLabel: "里程碑名称",
    category: "类别",
    milestone: "里程碑",
    noTagFound: "没有找到标签。标签需要在使用之前创建。",
    projectDialogFolderLabel: "项目保存路径",
    newProject: "新建项目",
    exportProject: "导出项目",
    importProject: "导入项目",
    settings: "设置",
    layoutAndOptions: "布局和选项",
    project: "项目",
    title: "标题",
    tags: "标签",
    backToProjects: "回到项目列表",
    searchInNotes: "搜索笔记 (CTRL + F)",
    addNewNote: "增加新的笔记",
    editProject: "编辑项目",
    milestones: "里程碑列表",
    noTagsCreated: "还没有创建标签",
    confirmDeleteMessage: "你确定要删除这个项目吗 ?",
    export: "导出",
    general: "一般",
    about: "关于",
    darkMode: "黑暗的主题",
    darkenToolbar: "Darken Toolbar",
    language: "语言",
    tasks: "任务",
    newTask: "新任务",
    edit: "编辑",
    save: "保存",
    cancel: "取消",
    browse: "浏览",
    done: "完成",
    close: "关闭",
    delete: "删除",
    add: "添加"
  }
};
