-- Apply after provisioning the dedicated Supabase project. All exposed data uses RLS.
create table public.workspaces (id uuid primary key default gen_random_uuid(), name text not null, owner_id uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.workspace_members (workspace_id uuid references public.workspaces(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, role text not null check(role in ('owner','editor','viewer')), primary key(workspace_id,user_id));
create table public.projects (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, name text not null, description text not null default '', data jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
alter table public.workspaces enable row level security; alter table public.workspace_members enable row level security; alter table public.projects enable row level security;
create policy "members read workspaces" on public.workspaces for select to authenticated using (owner_id=(select auth.uid()) or exists(select 1 from public.workspace_members m where m.workspace_id=id and m.user_id=(select auth.uid())));
create policy "owners manage workspaces" on public.workspaces for all to authenticated using (owner_id=(select auth.uid())) with check (owner_id=(select auth.uid()));
create policy "members read membership" on public.workspace_members for select to authenticated using (user_id=(select auth.uid()) or exists(select 1 from public.workspaces w where w.id=workspace_id and w.owner_id=(select auth.uid())));
create policy "owners manage membership" on public.workspace_members for all to authenticated using (exists(select 1 from public.workspaces w where w.id=workspace_id and w.owner_id=(select auth.uid()))) with check (exists(select 1 from public.workspaces w where w.id=workspace_id and w.owner_id=(select auth.uid())));
create policy "members read projects" on public.projects for select to authenticated using (exists(select 1 from public.workspaces w where w.id=workspace_id and (w.owner_id=(select auth.uid()) or exists(select 1 from public.workspace_members m where m.workspace_id=w.id and m.user_id=(select auth.uid())))));
create policy "editors manage projects" on public.projects for all to authenticated using (exists(select 1 from public.workspaces w where w.id=workspace_id and (w.owner_id=(select auth.uid()) or exists(select 1 from public.workspace_members m where m.workspace_id=w.id and m.user_id=(select auth.uid()) and m.role in ('owner','editor'))))) with check (exists(select 1 from public.workspaces w where w.id=workspace_id and (w.owner_id=(select auth.uid()) or exists(select 1 from public.workspace_members m where m.workspace_id=w.id and m.user_id=(select auth.uid()) and m.role in ('owner','editor')))));
